// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorite_movie.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovieFavorite = `-- name: CreateMovieFavorite :one
INSERT INTO favorite_movie(user_id, movie_id)
VALUES ($1, $2)
RETURNING user_id, movie_id
`

type CreateMovieFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) CreateMovieFavorite(ctx context.Context, arg CreateMovieFavoriteParams) (FavoriteMovie, error) {
	row := q.db.QueryRow(ctx, createMovieFavorite, arg.UserID, arg.MovieID)
	var i FavoriteMovie
	err := row.Scan(&i.UserID, &i.MovieID)
	return i, err
}

const deleteMovieFavorite = `-- name: DeleteMovieFavorite :execrows
DELETE FROM favorite_movie
WHERE user_id = $1 AND movie_id = $2
`

type DeleteMovieFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) DeleteMovieFavorite(ctx context.Context, arg DeleteMovieFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMovieFavorite, arg.UserID, arg.MovieID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMovieFavoriteList = `-- name: GetMovieFavoriteList :many
SELECT movie_id
FROM favorite_movie
WHERE user_id = $1
`

func (q *Queries) GetMovieFavoriteList(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getMovieFavoriteList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var movie_id pgtype.UUID
		if err := rows.Scan(&movie_id); err != nil {
			return nil, err
		}
		items = append(items, movie_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
