// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movie.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movie(title)
VALUES ($1)
RETURNING id, title, created_at
`

func (q *Queries) CreateMovie(ctx context.Context, title string) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie, title)
	var i Movie
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :execrows
DELETE FROM movie
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMovie, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMovieByID = `-- name: GetMovieByID :one

SELECT id, title, COALESCE(amount_rates, 0), COALESCE(rating, 0), created_at
FROM (
  select id, title, created_at from movie where id = $1
  ) m
LEFT JOIN ( 
  select movie_id, amount_rates, rating from movie_rating_view where movie_id = $1
) mrv ON m.id = mrv.movie_id
`

type GetMovieByIDRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	AmountRates int64            `json:"amount_rates"`
	Rating      float64          `json:"rating"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

// COALESCE and LEFT JOIN because rating exist if only at least one person rate movie
// TODO: check will 2 subquery be faster than one
func (q *Queries) GetMovieByID(ctx context.Context, id pgtype.UUID) (GetMovieByIDRow, error) {
	row := q.db.QueryRow(ctx, getMovieByID, id)
	var i GetMovieByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AmountRates,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const getMovieByTitle = `-- name: GetMovieByTitle :one

SELECT id, title, COALESCE(amount_rates, 0), COALESCE(rating, 0), created_at
FROM (
  select id, title, created_at from movie where title = $1
  ) m
LEFT JOIN movie_rating_view ON m.id = mrv.movie_id
`

type GetMovieByTitleRow struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	AmountRates int64            `json:"amount_rates"`
	Rating      float64          `json:"rating"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

// TODO: is it optimal (same as above query)
func (q *Queries) GetMovieByTitle(ctx context.Context, title string) (GetMovieByTitleRow, error) {
	row := q.db.QueryRow(ctx, getMovieByTitle, title)
	var i GetMovieByTitleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AmountRates,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const getMovieList = `-- name: GetMovieList :many
SELECT id, title, created_at
FROM movie
`

func (q *Queries) GetMovieList(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getMovieList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movie SET
  title = COALESCE($2, title)
WHERE id = $1
RETURNING id, title, created_at
`

type UpdateMovieParams struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, updateMovie, arg.ID, arg.Title)
	var i Movie
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}
