// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMovie(ctx context.Context, title string) (Movie, error)
	CreateMovieFavorite(ctx context.Context, arg CreateMovieFavoriteParams) (FavoriteMovie, error)
	CreateMovieRating(ctx context.Context, arg CreateMovieRatingParams) (RatedMovie, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (UserDatum, error)
	DeleteMovie(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteMovieFavorite(ctx context.Context, arg DeleteMovieFavoriteParams) (int64, error)
	DeleteMovieRating(ctx context.Context, arg DeleteMovieRatingParams) (int64, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error)
	// COALESCE and LEFT JOIN because rating exist if only at least one person rate movie
	// TODO: check will 2 subquery be faster than one
	GetMovieByID(ctx context.Context, id pgtype.UUID) (GetMovieByIDRow, error)
	// TODO: is it optimal (same as above query)
	GetMovieByTitle(ctx context.Context, title string) (GetMovieByTitleRow, error)
	GetMovieFavoriteList(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	GetMovieList(ctx context.Context) ([]Movie, error)
	GetMovieRatingList(ctx context.Context, userID pgtype.UUID) ([]GetMovieRatingListRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (UserDatum, error)
	GetUserByLogin(ctx context.Context, login string) (UserDatum, error)
	GetUserList(ctx context.Context) ([]UserDatum, error)
	UpdateMoveRating(ctx context.Context, arg UpdateMoveRatingParams) (RatedMovie, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UserDatum, error)
}

var _ Querier = (*Queries)(nil)
