// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rated_movie.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovieRating = `-- name: CreateMovieRating :one
INSERT INTO rated_movie (user_id, movie_id, rating)
VALUES ($1, $2, $3)
RETURNING user_id, movie_id, rating
`

type CreateMovieRatingParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
	Rating  pgtype.Int4 `json:"rating"`
}

func (q *Queries) CreateMovieRating(ctx context.Context, arg CreateMovieRatingParams) (RatedMovie, error) {
	row := q.db.QueryRow(ctx, createMovieRating, arg.UserID, arg.MovieID, arg.Rating)
	var i RatedMovie
	err := row.Scan(&i.UserID, &i.MovieID, &i.Rating)
	return i, err
}

const deleteMovieRating = `-- name: DeleteMovieRating :execrows
DELETE FROM rated_movie
WHERE user_id = $1 AND movie_id = $2
`

type DeleteMovieRatingParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) DeleteMovieRating(ctx context.Context, arg DeleteMovieRatingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMovieRating, arg.UserID, arg.MovieID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMovieRatingList = `-- name: GetMovieRatingList :many
SELECT movie_id, rating
FROM rated_movie
WHERE user_id = $1
`

type GetMovieRatingListRow struct {
	MovieID pgtype.UUID `json:"movie_id"`
	Rating  pgtype.Int4 `json:"rating"`
}

func (q *Queries) GetMovieRatingList(ctx context.Context, userID pgtype.UUID) ([]GetMovieRatingListRow, error) {
	rows, err := q.db.Query(ctx, getMovieRatingList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieRatingListRow
	for rows.Next() {
		var i GetMovieRatingListRow
		if err := rows.Scan(&i.MovieID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMoveRating = `-- name: UpdateMoveRating :one
UPDATE rated_movie SET
rating = COALESCE($3, rating)
WHERE user_id = $1 
  AND movie_id = $2
RETURNING user_id, movie_id, rating
`

type UpdateMoveRatingParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
	Rating  pgtype.Int4 `json:"rating"`
}

func (q *Queries) UpdateMoveRating(ctx context.Context, arg UpdateMoveRatingParams) (RatedMovie, error) {
	row := q.db.QueryRow(ctx, updateMoveRating, arg.UserID, arg.MovieID, arg.Rating)
	var i RatedMovie
	err := row.Scan(&i.UserID, &i.MovieID, &i.Rating)
	return i, err
}
