// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user_data(name, login, password)
VALUES ($1, $2, $3)
RETURNING id, name, login, password, is_admin, created_at
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Login    string `json:"login"`
	Password string `json:"-"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserDatum, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Login, arg.Password)
	var i UserDatum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM user_data
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, login, password, is_admin, created_at
FROM user_data
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (UserDatum, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i UserDatum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, name, login, password, is_admin, created_at
FROM user_data
WHERE login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (UserDatum, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i UserDatum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserList = `-- name: GetUserList :many
SELECT id, name, login, password, is_admin, created_at
FROM user_data
`

func (q *Queries) GetUserList(ctx context.Context) ([]UserDatum, error) {
	rows, err := q.db.Query(ctx, getUserList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDatum
	for rows.Next() {
		var i UserDatum
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Login,
			&i.Password,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE user_data SET
  name = COALESCE($2, name),
  login = COALESCE($3, login),
  password = COALESCE($4, password)
WHERE id = $1
RETURNING id, name, login, password, is_admin, created_at
`

type UpdateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     *string     `json:"name"`
	Login    *string     `json:"login"`
	Password *string     `json:"-"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UserDatum, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Login,
		arg.Password,
	)
	var i UserDatum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}
